from FA2_Interference_JHU_rw_HZZ import FA2_Interference_JHU_rw_HZZ
from FA3_Interference_JHU_ggHSyst_rw_HZZ import FA3_Interference_JHU_ggHSyst_rw_HZZ
from FL1_Interference_JHU_rw_HZZ import FL1_Interference_JHU_rw_HZZ
from FL1Zg_Interference_JHU_rw_HZZ import FL1Zg_Interference_JHU_rw_HZZ
from SpinZeroStructure import MultiSignalSpinZeroHiggs

class FA2_Interference_JHU_rw_HZZ_HTT_Combination(FA2_Interference_JHU_rw_HZZ, MultiSignalSpinZeroHiggs): pass
class FA3_Interference_JHU_ggHSyst_rw_HZZ_HTT_Combination(FA3_Interference_JHU_ggHSyst_rw_HZZ, MultiSignalSpinZeroHiggs): pass
class FL1_Interference_JHU_rw_HZZ_HTT_Combination(FL1_Interference_JHU_rw_HZZ, MultiSignalSpinZeroHiggs): pass
class FL1Zg_Interference_JHU_rw_HZZ_HTT_Combination(FL1Zg_Interference_JHU_rw_HZZ, MultiSignalSpinZeroHiggs): pass
